name: Update README cards

on:
  schedule:
    - cron: "0 * * * *"  # This runs once every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: generate snake
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake-catppuccin-mocha.svg?color_snake=#f5c2e7&color_dots=#312c42,#62537f,#8570a6,#a88bcf,#cba6f7

      - name: Generate readme activities
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          FILTER_EVENTS: "PushEvent,WatchEvent,IssueCommentEvent,IssuesEvent,PullRequestEvent,ReleaseEvent"

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=catppuccin_mocha&hide_border=true
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=395&theme=catppuccin_mocha&hide_border=true
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update README cards" || exit 0
          git push origin main
